### PR TITLE
Add infos in readme to fix unmet peer dependencies

### PR DESCRIPTION
**Pull request by jonasmonnier**
Not sure about react and react-dom versions you use but I had unmet peer depencencies after running npm install... Fixed like this. It is normal to do the installation manually?

### CODE REVIEW

**Comment by Natim** [comment]
Apparently they are in peerDependencies here: https://github.com/Kinto/formbuilder/blob/master/package.json#L20-L23

@n1k0 I don't know what it means, should we move them to dependency then?

**Comment by jonasmonnier** [comment]
Found this :
"We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies."

http://blog.npmjs.org/post/110924823920/npm-weekly-5

**Comment by Natim** [comment]
According to https://codingwithspike.wordpress.com/2016/01/21/dealing-with-the-deprecation-of-peerdependencies-in-npm-3/ we should get rid of peerDependencies

**Comment by almet** [comment]
Thanks for opening the pull request. As @natim mentioned, I believe we should put them in dependencies directly rather than fixing it in the README :)

**Comment by Natim** [comment]
@jonasmonnier Would you like to update your PR with that change then? I would be glad to merge it :+1:

**Comment by almet** [comment]
Thanks Jonas!

**Comment by jonasmonnier** [comment]
That's done. I set ^0.14.8 for both react and react dom (latest version of 0.14.x).
Thank you :)

**Pull request merged**
