### PR TITLE
Better wording for the submit a form button

### PR DESCRIPTION
**Pull request by almet**
What do you think @Natouille ?

### CODE REVIEW

**Comment by DirtyF** [comment]
What does this button do? It's not clear at all without context.

**Comment by almet** [comment]
This is taken from https://github.com/Kinto/formbuilder/issues/119. The button goes back to the welcome screen.

**Comment by DirtyF** [comment]
To the user point of view what it really does is save the form, so I would simply display "save your form".
I would not add delete link here, but in a settings menu, or in a list view later if one could edit many forms.

**Comment by almet** [comment]
Updated.

**Comment by Natouille** [comment]
Maybe "clear form" instead of delete form ?

**Pull request merged**
