### PR TITLE
Add widgets on simple click

### LINKED ISSUE #35: Add widgets on simple click
Currently it works using dragndrop. We should keep the dragndrop for the reorganisation of the widgets but we don't need to dragndrop them when they're first added.

### PR DESCRIPTION
**Pull request by almet**
Fix #35

### CODE REVIEW

**Comment by Natim** [comment]
r+

**Comment by QuentinRoy** [comment]
You fully removed the drag-and-drop ability? It can be handy if you want to insert a widget between two others.

**Comment by almet** [comment]
Yes, I removed the drag-and-drop ability from the menu (you can still move the items between them afterwards).Try adding

Do you have in mind a way to either click on a widget to insert it or drag it to start the drag-and-drop process? I thought these two were mutually exclusive, but it might not be true, we should give it a go to see how that feels. See #48.

**Comment by QuentinRoy** [comment]
They are not necessarily mutually exclusive in an interaction point of view. Drag and Tap/Click works pretty well in competition. As an example, in most web browsers, you can click on a link, but you can also drag then drop it as a new tab, a new fav or a new shortcut on the desktop.

However, how the two modes are delimited is important.
In general the idea is that the click mode is the first activated: it is activated as soon as the button is pressed), but if a distance threshold is crossed while the mouse button is pressed (or the finger is down), the click recognition is canceled and the drag mode is activated. Generally, this distance threshold can be tiny without impacting the usability.

Now, is it easy to implement with the `Draggable` component you are using? This I have no idea. I never implemented it with `React`.

**Pull request merged**
