### PR TITLE
issus 75 ux improvements

### PR DESCRIPTION
**Pull request by rlecellier**
screenshot from 2016-09-20 17-33-45
What in there : 
* remove FieldList/FieldListContainer sidebar, files are renamed FormActions/*Container.
* remove usage of draggable/dropable (it still work to order questions)
* remove Default view
* move view json link to createdForm view
* add addFieldDropdown that actualy replace FieldList component
* add some still for actions bar position.

livedemo: http://formbuilder.rlecellier.fr/#/builder

### CODE REVIEW

**Comment by DirtyF** [comment]
Nice work! I find this much more usable, I like the way it's evolving. 👏 

Here is some minor feedback aftet a first quick test:

Don't know why the second question field has an height:auto textarea who put too much space between the text and the focus:

textarea-height

The `Add Field` belongs to a button group and is right-aligned as the final calls to action. 
Shouldn't it be independant? it's a bit close, these are independant actions. Maybe the Reset/Save the Form could be sticky (or the opposite). Needs user testing.

Could we show users that a field is grabbable to reorder them with a default visible symbol?

I find it hard to distinguish different fields when they're not edited , should we add some space, border or light shadow?

Can we avoid the submit button in each field and auto-save when user clicks outside the current field?

I can open separate PR if these are out of the scope of this one.

**Comment by rlecellier** [comment]
About buttons positions, i like the way it is. At less it's there a huge ux mistake, i would prefer that smaller change been discute in a further issue.
My primary goal on this one is to merge the dropdown action in order to implement a "switch field" dropdown in the editable field's panel header.

_"show users that a field is grabbable"_
 it's a other issue, google do it by adding a little icon at the top/center of the question

_"[..]should we add some space, border or light shadow[..]"_
 i feel like the content of this review is already big enought. I we add too much here it'll never be merged :)

_Can we avoid the submit button in each field and auto-save when user clicks outside the current field?_
already proposed here https://github.com/Kinto/formbuilder/issues/104

**Comment by DirtyF** [comment]
@rlecellier you're right, let's :shipit: like this for now.

**Comment by almet** [comment]
That's really good, thanks for your work!

**Pull request merged**
