### PR TITLE
#202 fixed issue editing multi checkbox field

### PR DESCRIPTION
**Pull request by andydhobbs**
Changed config of multi checkbox field to resolve editing bug

### CODE REVIEW

**Comment by andydhobbs** [comment]
sorry, put wrong issue id in comment! it should have been #202

**Comment by almet** [comment]
@n1k0 could you review?

**Comment by andydhobbs** [comment]
there is still a minor display issue where the title "enum" is displayed on the field edit form. I am using the latest version of react-jsonschema-form which resolves this.

**Comment by almet** [comment]
Sorry for the time this took. Let's merge it!

**Pull request merged**
